# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: echo "REACT_APP_COGNITO_CLIENT_ID=${{secrets.REACT_APP_COGNITO_CLIENT_ID}}" >> .env
    - run: echo "REACT_APP_COGNITO_USER_POOL_ID=${{secrets.REACT_APP_COGNITO_USER_POOL_ID}}" >> .env
    - run: echo "REACT_APP_COGNITO_GOOGLE_CLIENT_ID=${{secrets.REACT_APP_COGNITO_GOOGLE_CLIENT_ID}}" >> .env
    - run: cat .env
    - run: npm run build:prod
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: us-east-1
    - run: aws s3 sync ./build s3://${{ vars.s3_bucket }} --delete --exclude "index.html"
    - run: aws s3 cp ./build/index.html s3://${{ vars.s3_bucket }}/index.html
    - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRO_ID }} --paths "/*"
